### ISSUE TITLE
Impossible to tell if the mob is tagged by someone else

### ISSUE THREAD

**Issue by mukhinv** [Ko0z/zUI#1]
Default blizz frames gray out if the mob is tagged, but zui unitfames don't.

**Comment by Ko0z** [comment]
Try again with only zUI addon enabled and so we can be certain that you dont have another addon that's causing it.

**Comment by mukhinv** [comment]
Tested, turns out you cannot see if the mod is tagged **only if you have NPC classes enabled**. I believe that NPC class color overrides the tagging coloring for the plate. Sorry for the confusion. Might still be worth it looking into though.

**Comment by Ko0z** [comment]
@mukhinv Alright thank you very much for the report! I’ll take a look at this and see what’s going on!

**Comment by Ko0z** [comment]
@mukhinv Alright yea I've tested this and know the reason for it showing a gray healthbar. It is becuase on some private servers some mobs hasnt been assigned a class, so if the server has implemented their own mobs for example, it's not uncommon that they "class-less" unfortunately.

But gray isnt a good color in these cases so I made it to show their hostility color in these situations so that there isnt any confusion about a mob being tagged or not.

I'm closing this now but feel free to reopen it if there's anything else you might find! Thanks again for reporting this 👍
