### ISSUE TITLE
Can't move loot roll frame

### ISSUE THREAD

**Issue by nickst0tt** [Ko0z/zUI#25]
Hi,

The loot roll frame appears in the middle of the screen and I can't shift-click and drag it.

I'm not sure if this positioning is intentional or a bug in addition to the un-draggability?

Thanks

**Comment by nickst0tt** [comment]
Sorry, not the loot window, but the frame when need/greed rolling in a party.

This frame is pinned to the middle of the screen, not  the cursor and it's quite jarring to me

**Comment by Ko0z** [comment]
Oh, I didnt read properly. Yea it made sense to put it there since I have castbar and target frames lower in the screen space. I suppose I could implement a feature to make it moveable, but not planned soon.

Also I think that, if there are multiple roll windows open at the same time, they stack downwards, below one another

**Comment by nickst0tt** [comment]
Okay, thanks very much anyway love the UI overall
